```python
当python检测到一些错误时，解释器无法继续执行，出现些错误提示
不捕获异常，出现异常时程序就不执行了。如果捕获了升序会继续执行
异常可以嵌套使用
--------------------------------------------
ctrl + c 也是一种异常 keyboardInterrupt
--------------------------------------------
# 异常可以分开捕获做不同处理
try:
    print(num)
    print("1")

# 多个异常时用元组
except (NameError, FileNotFoundError):
    print("有异常")

# 给异常起别名，当异常的名字很长的时候可以使用
# as是关键字，异常名字随便起是异常的引用，把异常核心的东西放在里面。
except IndexError as aaa:
    print(aaa)

# Exception可以捕获所有类型的异常(python3中的写法)
except Exception:
    print("有异常")
'''
# 捕获所有类型异常（python2中的写法）
except:
    print("有异常")
'''

# 没有任何异常时才会执行
else:
    print("没有任何异常")

# 有没有异常都会执行
finally:
    print("有没有异常都会执行")

print("-----")

```

异常传递

```python
如果函数出现异常但是没有try，会把异常传给函数调用者，调用者也没有try再往上传，直到有try的。
如果都没有try会把异常传给python解释器，它会结束程序。
def test1():
    print("--test1--1")
    print(num)
    print("--test1--2")

def test2():
    print("--test2--1")
    test1()
    print("--test2--2")

def test3():
    try:
        print("--test3--1")
        test2()
        print("--test3--2")
    except Exception as aaa:
        print(aaa)

test3()
print("运行结束")

打印结果
--test3--1
--test2--1
--test1--1
name 'num' is not defined
运行结束
```

抛出自定义异常

```python
有时需要自己设计一个异常手动触发异常。比如字符串要求大于6，但只有3，这时需要抛出自定义的异常
# 自定义继承Exception的异常
class MyError(Exception):
    def __init__(self, length, last):
        self.length = length
        self.last = last

def test():
    try:
        s = input("输入字符串：")
        if len(s) > 3:
            # raise引发一个自定义异常，需要一个异常对象。滴啊用方法创建异常对象.
            raise MyError(len(s), 3)
    except MyError as result:
        print("发现异常：输入的长度是%d,应该是%d"%(result.length, result.last))
    else:
        print("没有异常")

test()
```

异常处理中抛出异常

```python
正在处理异常，处理到一半不处理了再次抛出。
作用：捕获到异常的时候做些事情，然后再把异常抛出还按照以前执行。
try:
    print(a)

except Exception:
    print("处理到一半不处理了")
    raise

print("运行结束")
```

##### 打印报错在哪一行

```
import traceback

1.traceback.print_exc()是打印异常信息
2.traceback.format_exc()是获取异常信息的str
```

