##### 启动时报错

- 描述

  ```
  2021-12-08 17:53:11,814 alerta.plugins[106971]: [ERROR] Failed to load plugin 'remote_ip': 'remote_ip' [in /home/glfadd/Desktop/learn/alerta/alerta/utils/plugin.py:44]
  2021-12-08 17:53:12,563 alerta.plugins[106971]: [ERROR] Failed to load plugin 'reject': 'reject' [in /home/glfadd/Desktop/learn/alerta/alerta/utils/plugin.py:44]
  2021-12-08 17:53:14,933 alerta.plugins[106971]: [ERROR] Failed to load plugin 'heartbeat': 'heartbeat' [in /home/glfadd/Desktop/learn/alerta/alerta/utils/plugin.py:44]
  2021-12-08 17:53:14,934 alerta.plugins[106971]: [ERROR] Failed to load plugin 'blackout': 'blackout' [in /home/glfadd/Desktop/learn/alerta/alerta/utils/plugin.py:44]
  2021-12-08 17:53:14,936 alerta.plugins[106971]: [ERROR] Failed to load plugin 'forwarder': 'forwarder' [in /home/glfadd/Desktop/learn/alerta/alerta/utils/plugin.py:44]
  ```

- 原因

  ```
  没有安装这 5 个插件
  ```

- 解决办法

  ```
  ```

  

